baseURL = "https://aeonatelier.at/"
title = "aeon"
footer = "atelier@serbanganea.at"
theme = "vitae"
publishDir = "public"
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.de]
    disabled = false
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    title = 'aeon'
    weight = 1
    [languages.de.params]
      subtitle = 'architektur atelier'
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'aeon'
    weight = 2
    
    [languages.en.params]
      subtitle = 'architecture atelier'